# Generated by Django 4.0.2 on 2022-03-01 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='contributor',
            field=models.ManyToManyField(related_name='contributor', through='issuetracking.Contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
